version: '3'

services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checkout
    restart: unless-stopped

  checkout-main:
    depends_on:
      - postgres
    build: .
    ports:
      - 8080:8080

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://checkout-main:8089